### ISSUE TITLE
UnselectedIconColorProperty does not exists

### ISSUE THREAD

**Issue by BlazingGoblin** [joshuapolok/Xamarin-Font-Icons#3]
I think there is a typo in the binding property ( UnselectedIconColorColorProperty), so the property is unsettable in Xamarin Forms Styles

**Comment by joshuapolok** [comment]
There is a typo there, but that wouldn't interfere with the property. Can you give me an example of your issue? Thanks.

**Comment by BlazingGoblin** [comment]
Sure, i was writing a global style in XAML (xamarin.forms)

`<Style x:Key="TabUserStyle">
<Setter Property="BarBackgroundColor" Value="{StaticResource TLViolet}"/>
<Setter Property="UnselectedIconColor" Value="Color.White"/>
</Style>`

and at runtime (android) i get 
`Can't resolve UnselectedIconColorProperty on VectorIconTabbedPage`
while if i set the property as "UnselectedIconColorColor"
`The PropertyName of VectorIconTabbedPage.UnselectedIconColorColorProperty is not UnselectedIconColorColor`

Maybe it's just me setting it wrong, i admit i'm not too proficient with xaml (with code i can set it without any issue)

Thanks
